---
  - name: Add PHP 7 repository
    apt_repository: repo='ppa:ondrej/php-7.0'

  - name: Install PHP 7 FPM
    apt: pkg={{item}} state=installed update_cache=yes
    with_items:
        - php7.0-fpm
        - php7.0-curl
        - php7.0-json
        - php7.0-mcrypt
        - php7.0-mysql
        - php-user-cache

  - name: Copy php.ini config file
    copy: src={{ item.src }} dest={{ item.dest }} mode=644
    with_items:
        - { src: 'roles/php_install/files/php.ini', dest: '/etc/php/7.0/fpm/php.ini' }
        - { src: 'roles/php_install/files/www.conf', dest: '/etc/php/7.0/fpm/pool.d/www.conf' }
    notify: Restart PHP FPM
